import { writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import type { ExecutionPlan } from '../types/task.js';

/**
 * Google-style Design Doc generator.
 * Automatically created at Phase 1 as the canonical reference for all teams.
 *
 * Structure: Context → Goals/Non-goals → Design → Trade-offs → Alternatives
 */

export function generateDesignDoc(projectRoot: string, plan: ExecutionPlan): string {
  const dir = join(projectRoot, '.arc-reactor');
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });

  const teams = [...new Set(plan.tasks.map(t => t.team))];
  const featureIds = [...new Set(plan.tasks.map(t => t.featureId).filter(Boolean))];

  const lines = [
    `# Design Document`,
    ``,
    `> Auto-generated by Arc-Reactor Director`,
    `> Date: ${new Date().toISOString()}`,
    ``,
    `---`,
    ``,
    `## 1. Context & Scope`,
    ``,
    `**Goal:** ${plan.goal}`,
    `**Complexity:** ${plan.estimatedComplexity}`,
    `**Summary:** ${plan.analysis.summary}`,
    ``,
    `### Components`,
    ...plan.analysis.components.map(c => `- ${c}`),
    ``,
    `### Cross-cutting Concerns`,
    ...(plan.analysis.concerns.length > 0
      ? plan.analysis.concerns.map(c => `- ${c}`)
      : ['- None identified']),
    ``,
    `### Constraints`,
    ...(plan.analysis.constraints.length > 0
      ? plan.analysis.constraints.map(c => `- ${c}`)
      : ['- None identified']),
    ``,
    `---`,
    ``,
    `## 2. Goals & Non-goals`,
    ``,
    `### Goals`,
    ...plan.tasks.flatMap(t => t.acceptanceCriteria.map(ac => `- ${ac}`)).slice(0, 10),
    ``,
    `### Non-goals (v1)`,
    `- Performance optimization (handle after correctness)`,
    `- Internationalization (unless explicitly requested)`,
    `- Backward compatibility with legacy systems`,
    ``,
    `---`,
    ``,
    `## 3. Design`,
    ``,
    `### Teams Involved`,
    ...teams.map(t => `- **${t}**`),
    ``,
    `### Execution Waves`,
    ...plan.waves.map(w => {
      const waveTasks = w.taskIds.map(id => {
        const task = plan.tasks.find(t => t.id === id);
        return task ? `  - [${task.team}] ${task.title}` : `  - ${id}`;
      });
      return [`**Wave ${w.order}** (${w.taskIds.length} tasks)`, ...waveTasks, ''].join('\n');
    }),
    ``,
    `### Task Breakdown`,
    ``,
    ...plan.tasks.map(t => [
      `#### ${t.id}: ${t.title}`,
      `- **Team:** ${t.team}`,
      `- **Priority:** ${t.priority}`,
      t.featureId ? `- **Feature ID:** ${t.featureId}` : '',
      `- **Dependencies:** ${t.dependencies.length > 0 ? t.dependencies.join(', ') : 'None'}`,
      `- **Description:** ${t.description.slice(0, 200)}${t.description.length > 200 ? '...' : ''}`,
      `- **Acceptance Criteria:**`,
      ...t.acceptanceCriteria.map(ac => `  - [ ] ${ac}`),
      ``,
    ].filter(Boolean).join('\n')),
    ``,
    featureIds.length > 0 ? `### Feature IDs (Vibranium)\n${featureIds.map(f => `- ${f}`).join('\n')}\n` : '',
    `---`,
    ``,
    `## 4. Trade-offs`,
    ``,
    `| Decision | Trade-off | Rationale |`,
    `|----------|-----------|-----------|`,
    `| ${plan.estimatedComplexity} complexity | More/fewer phases | Balanced for quality vs speed |`,
    `| ${teams.length} teams | Parallelism vs coordination | Phase DAG enforces correct order |`,
    `| ${plan.waves.length} waves | Sequential safety vs parallel speed | Dry Run prevents file conflicts |`,
    ``,
    `---`,
    ``,
    `## 5. Alternatives Considered`,
    ``,
    `- **Single-agent execution:** Simpler but no parallelism, slower`,
    `- **No Phase DAG:** Faster but risk of file conflicts and team dependency violations`,
    `- **Skip QA phase:** Faster delivery but higher risk of undetected bugs`,
  ];

  const docPath = join(dir, 'design-doc.md');
  writeFileSync(docPath, lines.join('\n'));

  return docPath;
}
