import { execFileSync } from 'node:child_process';
import type { ExecutionResult } from './types/task.js';

export interface GitOpsConfig {
  autoCommit: boolean;
  autoBranch: boolean;
  branchPrefix: string;
  createPR: boolean;
}

export const DEFAULT_GIT_CONFIG: GitOpsConfig = {
  autoCommit: false,
  autoBranch: false,
  branchPrefix: 'feature/',
  createPR: false,
};

function runGit(args: string[], cwd: string): string {
  return execFileSync('git', args, { cwd, encoding: 'utf-8', stdio: 'pipe' });
}

function isGitRepo(cwd: string): boolean {
  try {
    runGit(['rev-parse', '--is-inside-work-tree'], cwd);
    return true;
  } catch {
    return false;
  }
}

export function initGitIfNeeded(cwd: string): void {
  if (!isGitRepo(cwd)) {
    runGit(['init'], cwd);
    runGit(['branch', '-m', 'main'], cwd);
  }
}

export function createFeatureBranch(cwd: string, featureId: string, prefix: string): string {
  const branchName = `${prefix}${featureId}`;
  try {
    runGit(['checkout', '-b', branchName], cwd);
  } catch {
    runGit(['checkout', branchName], cwd);
  }
  return branchName;
}

export function commitResults(cwd: string, result: ExecutionResult, featureId?: string): string | null {
  const files = result.results.flatMap((r) => r.outputs.map((o) => o.path));
  if (files.length === 0) return null;

  try {
    runGit(['add', ...files], cwd);

    const status = runGit(['status', '--porcelain'], cwd).trim();
    if (!status) return null;

    const goal = result.plan.goal;
    const teamNames = [...new Set(result.plan.tasks.map((t) => t.team))].join(', ');
    const featureRef = featureId ? `\nFeature-ID: ${featureId}` : '';
    const message = `feat: ${goal}\n\nTeams: ${teamNames}\nFiles: ${files.length}${featureRef}`;

    runGit(['commit', '-m', message], cwd);

    return runGit(['rev-parse', '--short', 'HEAD'], cwd).trim();
  } catch {
    return null;
  }
}

export function createPR(cwd: string, title: string, body: string): string | null {
  try {
    const output = execFileSync('gh', [
      'pr', 'create',
      '--title', title,
      '--body', body,
    ], { cwd, encoding: 'utf-8', stdio: 'pipe' });

    // gh pr create outputs the PR URL
    return output.trim();
  } catch {
    return null;
  }
}

export function pushBranch(cwd: string, branchName: string): boolean {
  try {
    runGit(['push', '-u', 'origin', branchName], cwd);
    return true;
  } catch {
    return false;
  }
}

export interface GitResult {
  branch?: string;
  commit?: string;
  prUrl?: string;
  pushed?: boolean;
}

export function autoGit(
  cwd: string,
  result: ExecutionResult,
  config: GitOpsConfig,
  featureId?: string,
): GitResult {
  if (!config.autoCommit && !config.autoBranch) return {};

  const output: GitResult = {};

  initGitIfNeeded(cwd);

  // 1. Feature 브랜치 생성 (feature/{feature-id})
  if (config.autoBranch) {
    const id = featureId || result.plan.goal
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 50);
    output.branch = createFeatureBranch(cwd, id, config.branchPrefix);
  }

  // 2. 생성된 파일 커밋
  if (config.autoCommit) {
    const sha = commitResults(cwd, result, featureId);
    if (sha) output.commit = sha;
  }

  // 3. Push + PR 생성
  if (config.createPR && output.branch && output.commit) {
    output.pushed = pushBranch(cwd, output.branch);

    if (output.pushed) {
      const title = `feat: ${result.plan.goal}`;
      const teams = [...new Set(result.plan.tasks.map((t) => t.team))].join(', ');
      const files = result.results.flatMap((r) => r.outputs.map((o) => o.path));
      const body = [
        `## Summary`,
        result.plan.analysis.summary,
        '',
        `## Teams: ${teams}`,
        `## Files (${files.length})`,
        ...files.map((f) => `- ${f}`),
        '',
        featureId ? `Feature-ID: ${featureId}` : '',
        '',
        `Generated by Arc-Reactor`,
      ].join('\n');

      output.prUrl = createPR(cwd, title, body) || undefined;
    }
  }

  return output;
}
